import type { NextPage } from "next";
import Head from "next/head";
import Home from "../src/components/home";
import Footer from "../src/components/layout/footer";
import Header from "../src/components/layout/header";

const HomePage: NextPage<any> = (props: any) => {

  const { lessons, searches } = props
    console.log("searche:", searches)
  return (
    <div>
      <Head>
        <title>Faradars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header {...searches}/>
      <main>
        <Home {...lessons} />
      </main>
      <Footer />
    </div>
  );
};
export async function getStaticProps() {
  const res = await fetch(`https://faradars.org/api/v1.1/application/home`);
  const lessons = await res.json();

  const repeatrRes = await fetch('https://faradars.org/api/v1.1/searches/repeated');
  const searches = await repeatrRes.json()


  return {
    props: {
      lessons: lessons.data,
      seraches: searches.data
    }
      || {},
    revalidate: 60 * 60,
  };
}

export default HomePage;
