import type { NextPage } from "next";
import Head from "next/head";
import Home from "../src/components/home";
import Footer from "../src/components/layout/footer";
import Header from "../src/components/layout/header";

const HomePage: NextPage<any> = (props: any) => {
  return (
    <div>
      <Head>
        <title>Faradars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Home {...props} />
      </main>
      <Footer />
    </div>
  );
};
export async function getStaticProps() {
  const res = await fetch(`https://faradars.org/api/v1.1/application/home`);
  const lessons = await res.json();

  const repeatRes = await fetch(
    "https://faradars.org/api/v1.1/searches/repeated"
  );
  const searches = await repeatRes.json();
  return {
    props:
      {
        lessons: lessons.data,
        searches: searches.data,
      } || {},
    revalidate: 60 * 60,
  };
}

export default HomePage;
