export const home_categories = [
  {
    id: 1,
    image: "/images/icons/programming.svg",
    url: "/how-to-learn/programming",
    title: "برنامه نویسی",
  },
  {
    id: 2,
    image: "/images/icons/stock-and-technical-analysis.svg",
    url: "/how-to-learn/stock-and-technical-analysis",
    title: "بورس و بازار سهام",
  },
  {
    id: 3,
    image: "/images/icons/startup-and-business.svg",
    url: "/how-to-learn/startup-and-business",
    title: "استارتاپ و کسب‌و‌کار",
  },
  {
    id: 4,
    image: "/images/icons/computer-science-and-engineering.svg",
    url: "/how-to-learn/computer-science-and-engineering",
    title: "مهندسی نرم‌افزار",
  },
  {
    id: 5,
    image: "/images/icons/artificial-intelligence.svg",
    url: "/how-to-learn/artificial-intelligence",
    title: "هوش مصنوعی",
  },
  {
    id: 6,
    image: "/images/icons/mathematics.svg",
    url: "/how-to-learn/mathematics",
    title: "ریاضیات",
  },
  {
    id: 7,
    image: "/images/icons/humanities.svg",
    url: "/how-to-learn/humanities",
    title: "علوم انسانی",
  },
  {
    id: 8,
    image: "/images/icons/art.svg",
    url: "/how-to-learn/art",
    title: "هنر",
  },
  {
    id: 9,
    image: "/images/icons/robotics.svg",
    url: "/how-to-learn/robotics",
    title: "رباتیک",
  },
  {
    id: 10,
    image: "/images/icons/statistics.svg",
    url: "/how-to-learn/statistics",
    title: "آمار و داده‌کاوی",
  },
  {
    id: 11,
    image: "/images/icons/matlab.svg",
    url: "/how-to-learn/matlab",
    title: "متلب و سیمیولینک",
  },
  {
    id: 12,
    image: "/images/icons/management.svg",
    url: "/how-to-learn/management",
    title: "مدیریت",
  },
  {
    id: 13,
    image: "/images/icons/english-language.svg",
    url: "/how-to-learn/english-language",
    title: "زبان انگلیسی",
  },
  {
    id: 14,
    image: "/images/icons/electrical-engineering.svg",
    url: "/how-to-learn/electrical-engineering",
    title: "مهندسی برق",
  },
  {
    id: 15,
    image: "/images/icons/mechanical-engineering.svg",
    url: "/how-to-learn/mechanical-engineering",
    title: "مهندسی مکانیک",
  },
  {
    id: 16,
    image: "/images/icons/civil-engineering.svg",
    url: "/how-to-learn/civil-engineering",
    title: "مهندسی عمران",
  },
  {
    id: 17,
    image: "/images/icons/architect-engineering.svg",
    url: "/how-to-learn/architect-engineering",
    title: "مهندسی معماری",
  },
  {
    id: 18,
    image: "/images/icons/control-engineering.svg",
    url: "/how-to-learn/control-engineering",
    title: "مهندسی کنترل",
  },
  {
    id: 19,
    image: "/images/icons/industrial-engineering.svg",
    url: "/how-to-learn/industrial-engineering",
    title: "مهندسی صنایع",
  },
  {
    id: 20,
    image: "/images/icons/academic-writing.svg",
    url: "/how-to-learn/academic-writing",
    title: "مدنگارش آکادمیک",
  },
  {
    id: 21,
    image: "/images/icons/microsoft-excel.svg",
    url: "/how-to-learn/microsoft-excel",
    title: "اکسل",
  },
  {
    id: 22,
    image: "/images/icons/photoshop-computer-design-and-graphics.svg",
    url: "/how-to-learn/photoshop-computer-design-and-graphics",
    title: "طراحی و گرافیک",
  },
  {
    id: 23,
    image: "/images/icons/webmastering.svg",
    url: "/how-to-learn/webmastering",
    title: "برنامه‌نویسی وب",
  },
  {
    id: 24,
    image: "/images/icons/wordpress.svg",
    url: "/how-to-learn/wordpress",
    title: "وردپرس",
  },
];

export const home_statistics = [
  {
    title: "حوزه تخصصی",
    statistics: 110
  },
  {
    title: "عنوان آموزشی",
    statistics: 5100
  },
  {
    title: "ساعت آموزش",
    statistics: 19000
  },
  {
    title: "نفر دانشجو",
    statistics: 1400000
  },
  {
    title: "نفر مدرس",
    statistics: 1600
  },
  {
    title: "ساعت حضور در دوره‌های آموزشی",
    statistics: 4300000
  },

];

 const jsonLandings:any = [   
    {
      "id": 36486,
      "title": "مجموعه آموزش برنامه‌نویسی",
      "slug": "programming",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">بدون شک، برنامه نویسی یکی از مهم&zwnj;ترین مهارت&zwnj;هایی است که امروزه نه تنها برای فارغ التحصیلان و دانشجویان رشته مهندسی کامپیوتر، بلکه برای سایر رشته&zwnj;ها و زمینه&zwnj;ها نیز به شکل ضروری، مورد نیاز است. هر ساله، بر تعداد موقعیت&zwnj;های شغلی که مرتبط با برنامه&zwnj;نویسی هستند و یا پیش&zwnj;نیاز اصلی آن&zwnj;ها برنامه&zwnj;نویسی است، افزوده می&zwnj;شود. از طرفی، بخشی جدا نشدنی از فرایند تحقیق و پژوهش در اکثر رشته&zwnj;های دانشگاهی امروزی، کار با کامپیوتر و توانایی پیاده&zwnj;سازی ایده&zwnj;ها و الگوریتم&zwnj;ها در قالب برنامه&zwnj;های کامپیوتری است. قطعا در این مسیر، دانشجویان نیازمند یادگیری و کسب مهارت&zwnj;های برنامه&zwnj;نویسی هستند.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p style=\"text-align:center\"><span style=\"color:#ff8700; font-size:18pt\"><strong>با آموزش&zwnj;های برنامه نویسی فرادرس، برنامه&zwnj;نویسی را یک بار و برای همیشه یاد بگیرید.</strong></span></p>\r\n\r\n<p style=\"text-align:center\"><span style=\"color:#993300; font-size:14pt\">همان طور که تا کنون هزاران نفر از مخاطبین فرادرس توانسته&zwnj;اند این کار را انجام دهند.</span></p>\r\n\r\n<p>&nbsp;</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2018/01/programming.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2018/01/programming.png.png",
      "icon": "",
      "count_product": 67,
      "attachment_id": 409101,
      "count_student": 311324,
      "total_time": 31606,
      "total_sales": 311324,
      "total_sales_30day": 6418,
      "count_instructor": 8,
      "seo_title": "آموزش برنامه نویسی - از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>برنامه نویسی</p>",
      "seo_metadesc": "مجموعه فیلم های آموزشی برنامه نویسی، به زبان های سی، سی پلاس پلاس، سی شارپ، جاوا، جاوا اسکریپت، PHP، ویژوال بیسیک، R، متلب و ... با تدریس مجرب ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 1758488,
      "title": "مجموعه آموزش بورس و تحلیل تکنیکال",
      "slug": "stock-and-technical-analysis",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">امروزه، یکی از فعالیت&zwnj;های مفید و پرسود اقتصادی، ورود به بازار سهام و فعالیت در آن است. اما این حوزه نیز مانند هر زمینه دیگری یک موضوع تخصصی محسوب می&zwnj;&zwnj;شود و هر فردی که علاقه&zwnj;&zwnj;مند به فعالیت در زمینه بورس و بازارهای مالی است، باید آموزش&zwnj;های لازم را برای یک فعالیت اقتصادی مطمئن، دیده باشد.</p>\r\n\r\n<p style=\"text-align:justify\">یکی از زمینه&zwnj;&zwnj;هایی که در آموزش&zwnj;های فرادرس به طور گسترده به آن پرداخته شده، حوزه بورس و بازار سرمایه است. تاکنون، بیش از 30 عنوان آموزشی در زمینه بورس، تحلیل تکنیکال و بازار سهام، در فرادرس ارائه و بیش از 200 هزار ثبت&zwnj;نام برای آموزش&zwnj;های این حوزه انجام شده است.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2021/01/16/burse-svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2021/01/16/burse-png.png",
      "icon": "",
      "count_product": 60,
      "attachment_id": 9229084,
      "count_student": 189669,
      "total_time": 17767,
      "total_sales": 189669,
      "total_sales_30day": 1977,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش بورس و تحلیل تکنیکال | مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>آموزش های بورس و تحلیل تکنیکال</p>",
      "seo_metadesc": "فیلم های آموزشی بورس و تحلیل تکنیکال و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 562350,
      "title": "مجموعه آموزش عمومی",
      "slug": "general",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2018/07/general.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2018/07/general.svg",
      "icon": "",
      "count_product": 80,
      "attachment_id": 562588,
      "count_student": 185520,
      "total_time": 16219,
      "total_sales": 185520,
      "total_sales_30day": 9474,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش های عمومی",
      "ext_title_short": "<p>آموزش های عمومی</p>",
      "seo_metadesc": null,
      "state_publish": "publish"
    },
    {
      "id": 748887,
      "title": "مجموعه آموزش نرم افزار های Adobe",
      "slug": "adobe",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2018/10/02.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2018/10/02.svg",
      "icon": "",
      "count_product": 53,
      "attachment_id": 749775,
      "count_student": 175766,
      "total_time": 15373,
      "total_sales": 175766,
      "total_sales_30day": 2624,
      "count_instructor": 3,
      "seo_title": "مجموعه آموزش نرم افزار های Adobe | فرادرس",
      "ext_title_short": "<p>آموزش نرم افزار های Adobe</p>",
      "seo_metadesc": "مجموعه آموزش نرم افزار های Adobe به صورت گام به گام با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55015,
      "title": "مجموعه آموزش مهارت های کاربردی کامپیوتر (ICDL)",
      "slug": "icdl",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/icdl.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/icdl.png.png",
      "icon": "",
      "count_product": 22,
      "attachment_id": 265308,
      "count_student": 167704,
      "total_time": 5076,
      "total_sales": 167704,
      "total_sales_30day": 5672,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش آی سی دی ال (ICDL) — مهارت های کامپیوتر — از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>مهارت های کاربردی کامپیوتر ICDL</p>",
      "seo_metadesc": "با آموزش‌ های مهارت‌ های هفت گانه کامپیوتر (ICDL) در فرادرس، به صورت اصولی و یک بار برای همیشه، کار با کامپیوتر را یاد بگیرید.",
      "state_publish": "publish"
    },
    {
      "id": 83705,
      "title": "مجموعه آموزش طراحی سایت",
      "slug": "web-design-and-programming",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/04/web-design-and-programming.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/04/web-design-and-programming.png.png",
      "icon": "",
      "count_product": 58,
      "attachment_id": 265290,
      "count_student": 163621,
      "total_time": 18240,
      "total_sales": 163621,
      "total_sales_30day": 2834,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش طراحی سایت | فرادرس",
      "ext_title_short": "<p>آموزش های طراحی سایت</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی طراحی و برنامه نویسی وب، به همراه آموزش نرم افزارهای تخصصی، توسط بهترین و مجرب ترین اساتید کشور، به زبان فارسی",
      "state_publish": "publish"
    },
    {
      "id": 140367,
      "title": "مجموعه آموزش مخصوص نوجوانان",
      "slug": "students-and-teenagers",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/09/students-and-teenagers.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/09/students-and-teenagers.png.png",
      "icon": "",
      "count_product": 21,
      "attachment_id": 265361,
      "count_student": 149250,
      "total_time": 6141,
      "total_sales": 149250,
      "total_sales_30day": 5664,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش مخصوص نوجوانان | فرادرس",
      "ext_title_short": "<p>آموزش های ویژه نوجوانان</p>",
      "seo_metadesc": "مجموعه ده ها ساعت از آموزش های دانش آموزی و نوجوانان فرادرس با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55032,
      "title": "مجموعه آموزش نرم افزارهای آفیس",
      "slug": "microsoft-office",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/microsoft-office.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/microsoft-office.png.png",
      "icon": "",
      "count_product": 26,
      "attachment_id": 265300,
      "count_student": 142670,
      "total_time": 5638,
      "total_sales": 142670,
      "total_sales_30day": 2421,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش آفیس (Microsoft Office) - از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>آموزش های آفیس Microsoft Office</p>",
      "seo_metadesc": "کتابخانه کاملی از فیلم های آموزشی مجموعه نرم افزاری مایکروسافت آفیس، مهارت های اساسی کار با آفیس را به صورت کامل خواهید آموخت.",
      "state_publish": "publish"
    },
    {
      "id": 55028,
      "title": "مجموعه آموزش اکسل",
      "slug": "microsoft-excel",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/microsoft-excel.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/microsoft-excel.png.png",
      "icon": "",
      "count_product": 20,
      "attachment_id": 265223,
      "count_student": 135644,
      "total_time": 4644,
      "total_sales": 135644,
      "total_sales_30day": 2147,
      "count_instructor": 1,
      "seo_title": "آموزش اکسل Excel - صفر تا صد | فرادرس",
      "ext_title_short": "<p>آموزش های اکسل Excel</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی نرم افزار اکسل به زبان فارسی، به صورت کاربردی و گام به گام، با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 58887,
      "title": "مجموعه آموزش مهندسی و علوم کامپیوتر",
      "slug": "computer-science-and-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">در دهه اخیر، رشد و پیشرفت کامپیوترها تحولات عظیمی را در جامعه بشری پدید آورده است. پیش&zwnj;بینی می&zwnj;شود در سال&zwnj;های آینده پیشرفت&zwnj;هایی در دنیای کامپیوترها حاصل شود که تا کنون هیچ گاه در طول تاریخ حیات بشر دیده نشده&zwnj;اند. نرخ تقاضا برای به&zwnj;کارگیری متخصصین علوم کامپیوتر تقریباً در همه حوزه&zwnj;ها و در نقاط مختلف دنیا بسیا بالا است. بنابراین، دلایل محکمی برای تحصیل در حوزه علوم کامپیوتر وجود دارند. بازار کار گسترده، درآمد بالا و فرصت تبدیل کردن جهان به جایی بهتر، تنها برخی از این دلایل محکم هستند.</p>\r\n\r\n<p style=\"text-align:justify\">با یادگیری مباحث علوم کامپیوتر و تحصیل در این زمینه، می&zwnj;توانید به مهارت&zwnj;ها و دانش مورد نیاز برای ورود به صنعت جذاب و دائماً در حال تحول علوم کامپیوتر مسلح شوید. مهم&zwnj;ترین جنبه علوم کامپیوتر حل مسئله است که مهارتی حیاتی در زندگی به حساب می&zwnj;آید. جویندگان علوم کامپیوتر طراحی، توسعه و تجزیه و تحلیل نرم&zwnj;افزار و سخت&zwnj;افزار مورد استفاده را برای حل مسائل در کسب و کارهای تجاری مختلف می&zwnj;آموزند. با توجه به اینکه کامپیوترها در حل مسئله&zwnj;های گوناگون برای کمک به جامعه بشری استفاده می&zwnj;شوند، یک جنبه انسانی و بشر دوستانه در علوم کامپیوتر نهفته است.</p>\r\n\r\n<p style=\"text-align:justify\">در دوره&zwnj;های تخصصی علوم کامپیوتر فرادرس، مهارت&zwnj;های مهندسی و طراحی نرم&zwnj;افزار، تفکر الگوریتمی، تعامل انسان و کامپیوتر، زبان&zwnj;های برنامه&zwnj;نویسی و تاریخچه محاسبات آموزش داده می&zwnj;شوند. دوره&zwnj;های آموزشی حوزه گسترده علوم کامپیوتر در فرادرس به شما کمک می&zwnj;کنند تا تفکر انتزاعی داشته باشید، به گونه&zwnj;ای روش&zwnj;مند نسبت به حل مسائل اقدام کنید و راه&zwnj;حل&zwnj;هایی معقول را توسعه دهید.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/computer-science.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/computer-science.png.png",
      "icon": "",
      "count_product": 43,
      "attachment_id": 265355,
      "count_student": 125400,
      "total_time": 30432,
      "total_sales": 125400,
      "total_sales_30day": 3051,
      "count_instructor": 1,
      "seo_title": "آموزش رشته کامپیوتر - مهندسی کامپیوتر و علوم کامپیوتر | فرادرس",
      "ext_title_short": "<p>دروس علوم و مهندسی کامپیوتر</p>",
      "seo_metadesc": "آموزش دروس علوم و مهندسی کامپیوتر به صورت گام به گام و به زبان ساده با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55526,
      "title": "مجموعه آموزش مهندسی عمران",
      "slug": "civil-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/civil-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/civil-engineering.png.png",
      "icon": "",
      "count_product": 87,
      "attachment_id": 265240,
      "count_student": 122415,
      "total_time": 38951,
      "total_sales": 122415,
      "total_sales_30day": 2513,
      "count_instructor": 1,
      "seo_title": "آموزش مهندسی عمران - گرایش های رشته عمران | فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی عمران</p>",
      "seo_metadesc": "مجموعه کامل فیلم های آموزشی مهندسی عمران و گرایش های مختلف آن، شامل صدها ساعت آموزش تخصصی حاوی مباحث تئوری و عملی، با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55043,
      "title": "مجموعه آموزش فتوشاپ، طراحی و گرافیک کامپیوتری",
      "slug": "photoshop-computer-design-and-graphics",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/computer-graphics.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/computer-graphics.png.png",
      "icon": "",
      "count_product": 57,
      "attachment_id": 265359,
      "count_student": 117694,
      "total_time": 15640,
      "total_sales": 117694,
      "total_sales_30day": 2018,
      "count_instructor": 5,
      "seo_title": "مجموعه آموزش فتوشاپ، طراحی و گرافیک کامپیوتری — از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>فتوشاپ، طراحی و گرافیک کامپیوتری</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی طراحی و گرافیک کامپیوتری به زبان فارسی، به صورت کاربردی و گام به گام، با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 568112,
      "title": "مجموعه آموزش ریاضیات",
      "slug": "mathematics",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">امروزه ریاضیات تقریباً در هر صنعتی، از علم و فناوری گرفته تا تجارت، فروش، مراقبت&zwnj;های بهداشتی و... کاربرد دارد. شاید آگهی&zwnj;های شغلی زیادی را نبینید که مستقیماً خواهان جذب &laquo;ریاضیدان&raquo; باشند، اما این رشته تحصیلی در موقعیت&zwnj;های زیادی ارزش ویژه&zwnj;ای دارد و توانایی فارغ&zwnj;التحصیلان آن در به کار بردن مفاهیم ریاضی برای حل مسائل، عناوین شغلی متنوعی را پیش&zwnj;روی آن&zwnj;ها قرار داده است. ریاضیدانان مهارت&zwnj;های منطقی و تجزیه و تحلیل بسیار خوبی دارند، سازمان&zwnj;دهی&zwnj;شده&zwnj;اند و راحت&zwnj;تر می&zwnj;توانند به مسائل را حل کنند.&nbsp;</p>\r\n\r\n<p style=\"text-align:justify\">فارغ&zwnj;التحصیلان رشته&zwnj;های مرتبط با ریاضی دو مسیر شغلی متمایز دارند: یک مسیر کار در دانشگاه به&zwnj;عنوان مدرس و محقق ریاضی، و دیگری مسیر کار در صنعت. امروزه، برخلاف گذشته، کار ریاضیدانان در صنعت بسیار رایج&zwnj; شده است و بسیاری از آن&zwnj;ها در زمینه&zwnj;های اقتصاد، هوش مصنوعی، علم داده، یادگیری ماشین و... مشغول به کار می&zwnj;شوند. واقعیت این است که شغل&zwnj;های مرتبط با صنعت بسیار متنوع&zwnj;ترند و فرصت&zwnj;های بی&zwnj;شماری را بر اساس علایق افراد در مسیر آن&zwnj;ها قرار می&zwnj;دهند. به عنوان مثال، افرادی که مدرک دانشگاهی در زمینه ریاضیات دارند و علاقه&zwnj;مند به فناوری هستند، می&zwnj;توانند به عنوان برنامه&zwnj;نویس کامپیوتر، توسعه&zwnj;دهنده نرم&zwnj;افزار یا دانشمند داده مشغول به کار شوند. سایر افراد با علایق تجاری می&zwnj;توانند به&zwnj;عنوان حسابرس یا تحلیلگر مالی فعالیت کنند یا برخی دیگر که به صنعت بهداشت و درمان علاقه دارند، می&zwnj;توانند دانشمند پزشکی شوند که شغل نسبتاً جدیدی است.&nbsp;</p>\r\n\r\n<p style=\"text-align:justify\">آنچه در این بین اهمیت دارد، یادگیری مفاهیم، کاربردها و همچنین کار با نرم&zwnj;افزارهای مرتبط با ریاضیات است، آن هم به &zwnj;شکل بهینه و باکیفیت. مجموعه آموزش&zwnj;های ریاضیات فرادرس با این رویکردها تهیه و تدوین شده&zwnj; است و گستره وسیعی از مباحث مربوط به این رشته را، از ریاضیات پایه دانشگاه برای رشته&zwnj;های مختلف تا مباحث کاربردی و پیش&zwnj;نیاز برای زمینه&zwnj;های مانند علوم کامپیوتر و هوش مصنوعی، در بر می&zwnj;گیرد. همچنین، آموزش&zwnj;های نرم&zwnj;افزارهای ریاضی فرادرس، گنجینه&zwnj;ای غنی را در اختیار دانشجویان قرار می&zwnj;دهند تا بتوانند در کار با آن&zwnj;ها به تسلط برسند و در مصاحبه&zwnj;های شغلی دست پر باشند.&nbsp;</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2018/07/math-landing.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2018/07/math-landing.svg",
      "icon": "",
      "count_product": 55,
      "attachment_id": 570507,
      "count_student": 116678,
      "total_time": 28959,
      "total_sales": 116678,
      "total_sales_30day": 3159,
      "count_instructor": 1,
      "seo_title": "آموزش ریاضیات دانشگاهی",
      "ext_title_short": "<p>آموزش های ریاضیات</p>",
      "seo_metadesc": null,
      "state_publish": "publish"
    },
    {
      "id": 55461,
      "title": "مجموعه آموزش هوش مصنوعی",
      "slug": "artificial-intelligence",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/computational-intelligence.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/computational-intelligence.png.png",
      "icon": "",
      "count_product": 40,
      "attachment_id": 265360,
      "count_student": 114838,
      "total_time": 20546,
      "total_sales": 114838,
      "total_sales_30day": 1977,
      "count_instructor": 12,
      "seo_title": "مجموعه آموزش هوش مصنوعی - از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>آموزش های هوش مصنوعی</p>",
      "seo_metadesc": "صدها ساعت آموزش تصویری مباحث تئوری و عملی هوش مصنوعی به صورت کاربردی و گام به گام، با تدریس مجرب ترین اساتید هوش مصنوعی کشور + پیاده سازی عملی",
      "state_publish": "publish"
    },
    {
      "id": 632531,
      "title": "مجموعه آموزش برنامه نویسی پایتون (Python)",
      "slug": "python-programming",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2018/08/phyton-programming.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2018/08/phyton-programming.svg",
      "icon": "",
      "count_product": 56,
      "attachment_id": 633315,
      "count_student": 113917,
      "total_time": 17698,
      "total_sales": 113917,
      "total_sales_30day": 4351,
      "count_instructor": 2,
      "seo_title": "آموزش برنامه نویسی پایتون | آموزش Python — مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>برنامه نویسی پایتون Python</p>",
      "seo_metadesc": "آموزش کامل برنامه نویسی پایتون - از صفر تا صد با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 6510866,
      "title": "مجموعه آموزش تحلیل تکنیکال - از مقدماتی تا پیشرفته",
      "slug": "technical-analysis",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2021/01/16/technical_analysis-svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2021/01/16/technical_analysis-png.png",
      "icon": "",
      "count_product": 17,
      "attachment_id": 9229091,
      "count_student": 113803,
      "total_time": 5851,
      "total_sales": 113803,
      "total_sales_30day": 822,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش تحلیل تکنیکال - از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>آموزش های تحلیل تکنیکال</p>",
      "seo_metadesc": "فیلم های آموزشی تحلیل تکنیکال و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 1057386,
      "title": "مجموعه آموزش نرم افزارهای مهندسی مکانیک",
      "slug": "mechanical-engineering-software",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2019/03/mechanical-engineering-software.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2019/03/mechanical-engineering-software.svg",
      "icon": "",
      "count_product": 102,
      "attachment_id": 1063690,
      "count_student": 104913,
      "total_time": 29248,
      "total_sales": 104913,
      "total_sales_30day": 2257,
      "count_instructor": 2,
      "seo_title": "نرم افزارهای مهندسی مکانیک | فرادرس",
      "ext_title_short": "<p>آموزش نرم افزارهای مهندسی مکانیک</p>",
      "seo_metadesc": "مجموعه کاملی از فیلم های آموزشی نرم افزارهای مهندسی مکانیک و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با تدریس مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 132166,
      "title": "مجموعه آموزش دروس مشترک رشته های فنی",
      "slug": "engineering-common-courses",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/08/engineering-common-courses.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/08/engineering-common-courses.png.png",
      "icon": "",
      "count_product": 26,
      "attachment_id": 265293,
      "count_student": 102189,
      "total_time": 16385,
      "total_sales": 102189,
      "total_sales_30day": 2971,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش دروس مشترک رشته های فنی | فرادرس",
      "ext_title_short": "<p>دروس مشترک رشته های فنی</p>",
      "seo_metadesc": "مجموعه کاملی از آموزش های دروس رشته های مختلف فنی و مهندسی، شامل صدها ساعت آموزش تخصصی به زبان فارسی با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 58553,
      "title": "مجموعه آموزش‌ مهندسی الکترونیک",
      "slug": "electronics-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/microcontrollers-and-digital-electronics.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/microcontrollers-and-digital-electronics.png.png",
      "icon": "",
      "count_product": 46,
      "attachment_id": 265378,
      "count_student": 96214,
      "total_time": 25309,
      "total_sales": 96214,
      "total_sales_30day": 1925,
      "count_instructor": 1,
      "seo_title": "آموزش مهندسی برق - الکترونیک | فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی الکترونیک</p>",
      "seo_metadesc": "کامل‌ترین مجموعه فیلم‌های آموزشی انواع میکروکنترلرها (شامل AVR، آردوینو، PIC و ...) و طراحی مدارهای الکترونیک دیجیتال، با مجرب‌ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 148889,
      "title": "مجموعه آموزش مهندسی معماری (Architecture)",
      "slug": "architect-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/10/architect-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/10/architect-engineering.png.png",
      "icon": "",
      "count_product": 71,
      "attachment_id": 265243,
      "count_student": 94856,
      "total_time": 25842,
      "total_sales": 94856,
      "total_sales_30day": 2047,
      "count_instructor": 2,
      "seo_title": "آموزش کامل مهندسی معماری Architecture - مقدماتی تا پیشرفته| فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی معماری</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی مهندسی معماری، شامل صدها ساعت آموزش تخصصی حاوی مباحث تئوری و عملی با تدریس مجرب ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 1057411,
      "title": "مجموعه آموزش نرم افزارهای مهندسی عمران",
      "slug": "civil-engineering-software",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2019/03/civil-engineering-software.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2019/03/civil-engineering-software.svg",
      "icon": "",
      "count_product": 80,
      "attachment_id": 1063857,
      "count_student": 90841,
      "total_time": 24286,
      "total_sales": 90841,
      "total_sales_30day": 1734,
      "count_instructor": 1,
      "seo_title": "نرم افزارهای مهندسی عمران | فرادرس",
      "ext_title_short": "<p>آموزش نرم افزارهای مهندسی عمران</p>",
      "seo_metadesc": "مجموعه کاملی از فیلم های آموزشی نرم افزارهای مهندسی عمران و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با تدریس مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 143455,
      "title": "راه اندازی و مدیریت سایت‎",
      "slug": "setup-and-manage-websites",
      "post_status": "draft",
      "excerpt": "",
      "content": "",
      "svg_image": "",
      "png_image": "",
      "icon": "",
      "count_product": 16,
      "attachment_id": null,
      "count_student": 87630,
      "total_time": 4497,
      "total_sales": 87630,
      "total_sales_30day": 749,
      "count_instructor": 1,
      "seo_title": "",
      "ext_title_short": null,
      "seo_metadesc": "",
      "state_publish": "draft"
    },
    {
      "id": 55502,
      "title": "مجموعه آموزش مهندسی صنایع",
      "slug": "industrial-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/dustrial-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/dustrial-engineering.png.png",
      "icon": "",
      "count_product": 84,
      "attachment_id": 265298,
      "count_student": 86674,
      "total_time": 24462,
      "total_sales": 86674,
      "total_sales_30day": 2916,
      "count_instructor": 1,
      "seo_title": "آموزش مهندسی صنایع | فرادرس",
      "ext_title_short": "<p>اموزش های مهندسی صنایع و تحقیق در عملیات</p>",
      "seo_metadesc": "مجموعه کاملی از آموزش‌ های فرادرس در زمینه مهندسی صنایع، شامل صدها ساعت آموزش تخصصی با مجرب ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 140927,
      "title": "مجموعه آموزش زبان خارجی",
      "slug": "foreign-languages",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">اساتید زبان بر این باورند که کودکان زبان&zwnj;های خارجی را بهتر از بزرگسالان فرا می&zwnj;گیرند. اما بسیاری از بزرگسالان با توجه به اهداف خود، به آموختن زبانی غیر از زبان مادری خود نیاز دارند. از آنجایی که زبان انگلیسی به عنوان زبان بین&zwnj;المللی رایج در سرتاسر دنیا شناخته شده است، به نظر می&zwnj;رسد که یادگیری آن امری ضروری باشد. اما در هر صورت، برای یاد گرفتن هر زبانی، در وهله اول باید با مهارت&zwnj;های آن آشنا شویم. چهار مهارت اصلی در یادگیری هر زبانی زبان&zwnj; شامل &laquo;شنیدن&raquo;، &laquo;خواندن&raquo;، &laquo;نوشتن&raquo; و &laquo;سخن گفتن&raquo; می&zwnj;شود و در کنار این مهارت&zwnj;ها، بهبود دایره واژگان و تسلط بر گرامر می&zwnj;تواند تأثیر بسیار زیادی در پیشرفت زبان&zwnj;آموزان داشته باشد.</p>\r\n\r\n<p style=\"text-align:justify\">برای بسیاری از افرادی که در سطح مقدماتی هستند یا می&zwnj;خواهند از صفر شروع کنند، ضرورت آشنایی با دوره&zwnj;های آموزشی یا منابع کمک&zwnj;آموزشی نظیر کتاب، فیلم&zwnj;های آموزشی، اپلیکیشن یا پادکست، بیشتر از هر زمان دیگری حس می&zwnj;شود. در مجموعه دوره&zwnj;های آموزش زبان فرادرس، مباحث مربوط به یادگیری زبان&zwnj;های خارجی مانند انگلیسی، آلمانی، فرانسه، دانمارکی و عربی ارائه شده است. این فیلم&zwnj;های آموزشی، به زبان ساده و با مثال&zwnj;های متعدد در اختیار افراد قرار گرفته است که هم برای زبان&zwnj;آموزان دوره مقدماتی و هم برای دانشجویان مقاطع مختلف مناسب است. همچنین، در خصوص آموزش&zwnj;های زبان انگلیسی، برای کسانی که قصد مهاجرت به کشورهای دیگر را دارند و می&zwnj;بایست در آزمون&zwnj;های بین&zwnj;المللی نظیر آیلتس، تافل یا دولینگو شرکت کنند، ویدئوهای آموزشی متعددی تهیه شده است.&nbsp;</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/10/landing-horizontal.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/10/landing-horizontal.png.png",
      "icon": "",
      "count_product": 69,
      "attachment_id": 301244,
      "count_student": 86179,
      "total_time": 15970,
      "total_sales": 86179,
      "total_sales_30day": 3215,
      "count_instructor": 2,
      "seo_title": "مجموعه آموزش‌ های زبان خارجی | فرادرس",
      "ext_title_short": "<p>آموزش های زبان خارجی</p>",
      "seo_metadesc": "ده‌ها ساعت آموزش تصویری مباحث آموزش های زبان خارجی به صورت کاربردی و گام به گام، با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 437085,
      "title": "مجموعه آموزش فتوشاپ (Photoshop)",
      "slug": "photoshop",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p>&nbsp;</p>\r\n\r\n<div id=\"gtx-trans\" style=\"left:1064px; position:absolute; top:-12px\">\r\n<div class=\"gtx-trans-icon\">&nbsp;</div>\r\n</div>\r\n\r\n<div id=\"gtx-trans\" style=\"left:1064px; position:absolute; top:-12px\">\r\n<div class=\"gtx-trans-icon\">&nbsp;</div>\r\n</div>",
      "svg_image": "https://faradars.org/wp-content/uploads/2019/03/photoshop.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2019/03/photoshop.svg",
      "icon": "",
      "count_product": 25,
      "attachment_id": 1061845,
      "count_student": 84514,
      "total_time": 5122,
      "total_sales": 84514,
      "total_sales_30day": 1401,
      "count_instructor": 1,
      "seo_title": "آموزش فتوشاپ (Photoshop) از مبتدی تا پیشرفته | فرادرس",
      "ext_title_short": "آموزش های فتوشاپ Photoshop",
      "seo_metadesc": "مجموعه کاملی از فیلم های آموزشی فتوشاپ (Photoshop) و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 55481,
      "title": "مجموعه آموزش مهندسی برق",
      "slug": "electrical-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">اغلب وسایل کاربردی زندگی&zwnj; روزمره ما یک ويژگی مشترک دارند و آن این است که با &laquo;برق&raquo; کار می&zwnj;کنند. همین ویژگی ساده نشان می&zwnj;دهد که مهندسی برق در دنیای امروز تا چه اندازه از اهمیت برخوردار است. هر جا که ردی از برق باشد، از یک سیگنالِ ضعیفِ بدن انسان گرفته تا خطوط انتقال فشار قوی، با مهندسی برق نیز ارتباطی وجود دارد.</p>\r\n\r\n<p style=\"text-align:justify\">مهندسی برق شاخه&zwnj;ای از مهندسی است که گرایش&zwnj;ها و زمینه&zwnj;های تحصیلی متنوعی، از جمله الکترونیک، قدرت، کنترل مخابرات، پردازش سیگنال و مهندسی پزشکی دارد. مهندسی الکترونیک شاخه&zwnj;ای از مهندسی برق است که با استفاده از مفاهیم مدارها و کاربرد وسایل الکترونیکی مانند مدارهای مجتمع و ترانزیستورها مرتبط است. مهندسان قدرت وظیف تولید تا توزیع برق را بر عهده دارند. کنترل و خودکارسازی فرایندهای صنعتی از وظایف ذاتی مهندسان کنترل است. ارتباطات پیشرفته از راه دور در حوزه کاری مهدسان مخابرات قرار می&zwnj;گیرد. کسانی که در زمینه پردازش سیگنال کار می&zwnj;کنند، با سیگنال&zwnj;ها و داده&zwnj;های مختلف، از سیگنال&zwnj;های حیاتی بدن انسان گرفته تا شناسایی پلاک خودروها سر و کار دارند. مهندسان پزشکی نیز همواره در پی یافتن راه&zwnj;هایی برای کمک به فرایندهای پزشکی از راه&zwnj;های مهندسی مختلف هستند.</p>\r\n\r\n<p style=\"text-align:justify\">البته امروزه با پیشرفت&zwnj; بسیار سریع فناوری تمایز بین رشته&zwnj;ها کمتر شده و رویکرد بین&zwnj;رشته&zwnj;ای زمینه&zwnj;های مختلف مهندسی برق با اقبال عمومی پژوهشگران و فناوران مواجه شده است. این رویکرد بین&zwnj;رشته&zwnj;ای در کنار رایج شدن روش&zwnj;های جدید آموزشِ بهینه&zwnj;تر از نظر زمان و هزینه، راه را برای یادگیری و آموزشی روشن&zwnj;تر و هموارتر از گذشته کرده است. دیگر این روزها نشستن روی صندلی&zwnj;های دانشگاه تنها انتخاب ممکن برای یادگیری نیست. کافی است هر مسیر یادگیری موضوع یا مهارت مورد نظرتان را مشخص کنید.</p>\r\n\r\n<p style=\"text-align:justify\">فرادرس آموزش&zwnj;های متنوعی در زمینه&zwnj;های مختلف و سطوح پایه تا پیشرفته مهندسی برق تهیه، تدوین و ارائه کرده که با توجه به مسیر یادگیریتان می&zwnj;توانید از آن&zwnj;ها استفاده کنید. فرقی ندارد هدفتان یادگیری مفاهیم علوم پایه دانشگاهی، مدارهای الکتریکی یا الکترومغناطیس باشد، یا به دنبال یادگیری مباحث تخصصی در زمینه طراحی مدارهای الکترونیکی فرکانس بالا و سیستم&zwnj;های کنترل پیشرفته صنعتی باشید، یا بخواهید در کار با نرم&zwnj;افزارهای طراحی بردهای الکترونیکی و شبیه&zwnj;سازی سیستم&zwnj;های قدرت تسلط پیدا کنید؛ فرادرس همیشه و همه جا در دسترس شماست و می&zwnj;توانید با جست&zwnj;وجو در بین هزاران ساعت آموزش، به جمع میلیونی دانشجویان فرادرس بپیوندید.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/electrical-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/electrical-engineering.png.png",
      "icon": "",
      "count_product": 56,
      "attachment_id": 265259,
      "count_student": 81751,
      "total_time": 36379,
      "total_sales": 81751,
      "total_sales_30day": 2165,
      "count_instructor": 1,
      "seo_title": "آموزش مهندسی برق - گرایش های رشته برق | فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی برق</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم‌های آموزشی مهندسی برق در گرایش های مختلف، شامل صدها ساعت آموزش تخصصی حاوی مباحث تئوری و عملی به زبان فارسی با تدریس مجرب ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 55425,
      "title": "مجموعه آموزش داده کاوی و یادگیری ماشین",
      "slug": "machine-learning-and-data-mining",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">یکی از تفاوت&zwnj;های اصلی میان انسان و کامپیوتر این است که انسان از تجربیات گذشته می&zwnj;آموزد، اما کامپیوتر یا ماشین این چنین نیست و باید تک تک دستورالعمل&zwnj;ها را برای آن مشخص کرد. در واقع کامپیوترها ماشین&zwnj;هایی اکید و بدون شعور متعارف هستند. این یعنی اگر بخواهیم کامپیوترها کاری را انجام بدهند، باید دستورالعمل&zwnj;های لازم را به صورت جزئی و گام به گام برای آن&zwnj;ها تعریف و دقیقاً مشخص کرد که چه کاری باید انجام شود.</p>\r\n\r\n<p style=\"text-align:justify\">به همین دلیل، اسکریپت&zwnj;ها و برنامه&zwnj;های کامپیوتری نوشته می&zwnj;شوند تا از این طریق دستورالعمل&zwnj;های مورد نیاز یک به یک توسط کامپیوترها اجرا شوند. در اینجا اهمیت یادگیری ماشین مشخص می&zwnj;شود، چرا که به واسطه آن مرز میان انسان و ماشین به میزان زیادی از بین می&zwnj;رود و ماشین هم به مانند انسان می&zwnj;تواند از تجربیات گذشته درس بگیرد. یادگیری ماشین یعنی پیاده&zwnj;سازی روش&zwnj;هایی که به وسیله آن&zwnj;ها ماشین بتواند با استفاده از داده&zwnj;های مربوط به تجربیات گذشته آموزش ببیند و عملکرد خود را بر اساس این اطلاعات بهبود دهد.</p>\r\n\r\n<p style=\"text-align:justify\">در دوره&zwnj;های آموزش یادگیری ماشین فرادرس بر ایجاد سیستم&zwnj;هایی تمرکز شده است که مقادیر حجیمی از داده&zwnj;ها را استفاده می&zwnj;کنند و این حجم زیاد داده&zwnj;ها را برای فرآیند یادگیری به کار می&zwnj;گیرند. از جمله عناوین دوره&zwnj;های آموزشی یادگیری ماشین فرادرس می&zwnj;توان به الگوریتم&zwnj;های پیش&zwnj;بینی، پردازش زبان طبیعی و بازشناسی الگوی آماری اشاره کرد.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/machine-learning-and-pattern-recognition.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/machine-learning-and-pattern-recognition.png.png",
      "icon": "",
      "count_product": 40,
      "attachment_id": 265286,
      "count_student": 81174,
      "total_time": 19355,
      "total_sales": 81174,
      "total_sales_30day": 2415,
      "count_instructor": 3,
      "seo_title": "مجموعه آموزش داده کاوی و یادگیری ماشین — از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>داده کاوی و یادگیری ماشین</p>",
      "seo_metadesc": "مجموعه آموزش داده کاوی و یادگیری ماشین - مقدماتی تا پیشرفته به صورت گام به گام با مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55484,
      "title": "مجموعه آموزش‌ مهندسی قدرت",
      "slug": "power-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/power-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/power-engineering.png.png",
      "icon": "",
      "count_product": 69,
      "attachment_id": 265282,
      "count_student": 78669,
      "total_time": 30291,
      "total_sales": 78669,
      "total_sales_30day": 1587,
      "count_instructor": 1,
      "seo_title": "آموزش مهندسی برق - قدرت | فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی قدرت</p>",
      "seo_metadesc": "مجموعه کاملی از آموزش‌ های فرادرس در زمینه مهندسی قدرت و مباحث مرتبط با آن، شامل صدها ساعت آموزش تخصصی با مجرب‌ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 132236,
      "title": "دروس مهندسی کنترل",
      "slug": "control-engineering-courses",
      "post_status": "draft",
      "excerpt": "",
      "content": "&nbsp;\r\n<p style=\"text-align: justify;\">مهندسی کنترل (Control engineering)، یکی از گرایش های مهندسی برق می باشد که در زمینه های گوناگونی کاربرد دارد. کنترل خطی درس پایه ای این رشته است که دانشجویان با این درس وارد مباحث اصلی این رشته می شوند. همچنین دروسی مثل کنترل غیرخطی در ادامه مباحث پر اهمیت این رشته می باشد. با توجه به این موارد، آموزش کامل این دروس در فرادرس، می تواند کمک شایانی به دانشجویان در فراگیری این مباحث بکند.</p>\r\n&nbsp;",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/08/control-engineering-courses.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/08/control-engineering-courses.png.png",
      "icon": "",
      "count_product": 49,
      "attachment_id": 265328,
      "count_student": 76951,
      "total_time": 22385,
      "total_sales": 76951,
      "total_sales_30day": 1564,
      "count_instructor": 4,
      "seo_title": "دروس مهندسی کنترل",
      "ext_title_short": null,
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی دروس مهندسی کنترل، شامل صدها ساعت آموزش تخصصی به زبان فارسی با تدریس مجرب ترین اساتید مهندسی برق کشور",
      "state_publish": "draft"
    },
    {
      "id": 9208120,
      "title": "مجموعه آموزش توسعه مهارت فردی",
      "slug": "development-of-individual-skills",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">می&zwnj;توان گفت که &laquo;توسعه فردی&raquo; (Personal Development) با مبحث &laquo;خودآگاهی&raquo; (Self-Awareness) گره خورده است. توسعه فردی به شما این فرصت را می&zwnj;دهد که نسبت به بخش&zwnj;های مختلف زندگی خود دیدگاهی صادقانه پیدا کنید و بخش&zwnj;های نیازمند بهبود را بشناسید. در این فرآیند متوجه می&zwnj;شوید که واقعاً چه کسی هستید، چه مفاهیمی برای شما &laquo;ارزش&raquo; تلقی می&zwnj;شوند و هدف نهایی شما در زندگی چیست.</p>\r\n\r\n<p style=\"text-align:justify\">به طور کلی دوره&zwnj;های آموزشی توسعه فردی، استراتژی&zwnj;ها و چارچوب&zwnj;های رشد فردی، تعیین هدف و بهبود شخصی را به شما می&zwnj;آموزد. در این دوره&zwnj;ها اغلب شیوه مدیریت امور مالی فردی، سخنرانی مؤثر، تصمیم&zwnj;گیری اخلاقی و تفکر خلاقانه را خواهید آموخت. از مهارت&zwnj;های دیگر در زمینه توسعه فردی می&zwnj;توان به برقراری ارتباط، سازمان&zwnj;دهی، حل مسئله، بهبود اعتمادبه&zwnj;نفس و توانایی وفق پیدا کردن با شرایط را نام برد.</p>\r\n\r\n<p style=\"text-align:justify\">فیلم&zwnj;های آموزشی فرادرس در زمینه توسعه فردی به شما کمک می&zwnj;کند که چشم&zwnj;اندازها و اهداف شخصی خود در زندگی را به شکلی واضح&zwnj;تر معین کنید. زمانی که اهداف خود را به طور دقیق مشخص کنید، برنامه&zwnj;ریزی برای رسیدن به آن&zwnj;ها ساده&zwnj;تر خواهد شد.<br />\r\n&nbsp;</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2021/08/26/individual_skills-svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2021/08/26/individual_skills-png.png",
      "icon": "",
      "count_product": 35,
      "attachment_id": 9242904,
      "count_student": 76774,
      "total_time": 8242,
      "total_sales": 76774,
      "total_sales_30day": 1496,
      "count_instructor": 1,
      "seo_title": "آموزش کامل توسعه مهارت فردی | فرادرس",
      "ext_title_short": "<p>آموزش های توسعه مهارت فردی</p>",
      "seo_metadesc": "آموزش کامل برای ارتقای مهارت های فردی همراه با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55492,
      "title": "مجموعه آموزش مهندسی مکانیک",
      "slug": "mechanical-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">تجهیزات، ماشین&zwnj;آلات و سیستم&zwnj;های مکانیکی، بخش جدایی&zwnj;ناپذیر زندگی انسان امروزی هستند. ماشین&zwnj;هایی که مسافران را جابجا می&zwnj;کنند، آسانسوری که افراد را از یک طبقه ساختمان به طبقه دیگر می&zwnj;برد، وسایلی که به منظور کاهش یا افزایش دمای محیط مورد استفاده قرار می&zwnj;گیرند و لوله&zwnj;هایی که آب را به داخل یا خارج از ساختمان انتقال می&zwnj;دهند، از مثال&zwnj;های پرکاربرد و شناخته شده سیستم&zwnj;های مکانیکی هستند. به طور کلی، هر وسیله متحرک یا دارای قطعه متحرک، یک سیستم مکانیکی محسوب می&zwnj;شود. از این&zwnj;رو، انسان&zwnj;ها همواره با سیستم&zwnj;های مکانیکی سر و کار دارند.</p>\r\n\r\n<p style=\"text-align:justify\">هنگام کار با تجهیزات مکانیکی یا مشاهده عملکرد آن&zwnj;ها، ممکن است از خود بپرسید که &laquo;این تجهیزات چگونه کار می&zwnj;کنند؟&raquo; پاسخ این سوال در علم مهندسی مکانیک نهفته است. مهندسی مکانیک، با تکیه بر قواعد ریاضی و فیزیک و ترکیب آن&zwnj;ها با علم مواد، زمینه طراحی و ساخت سیستم&zwnj;های مکانیکی را برای کاربری&zwnj;های مختلف فراهم می&zwnj;کند. سینماتیک، دینامیک، مکانیک سیالات، انتقال حرارت، مدل&zwnj;سازی، مقاومت مصالح و آیرودینامیک، از دیگر علوم مرتبط با مهندسی مکانیک هستند.</p>\r\n\r\n<p style=\"text-align:justify\">دوره&zwnj;های مهندسی مکانیک فرادرس، مباحث و نرم افزارهای تخصصی مورد نیاز برای یادگیری اصولی مبانی سیستم&zwnj;های مکانیکی و طراحی آن&zwnj;ها را پوشش می&zwnj;دهند. تدریس این دوره&zwnj;ها توسط اساتید مجرب و در سطوح مقدماتی تا پیشرفته انجام می&zwnj;شود. آموزش&zwnj;های فرادرس، مناسب تمام افراد علاقه&zwnj;مند، دانشجویان و حتی فارغ&zwnj;التحصیلانی است که به دنبال ارتقا دانش خود در گرایش&zwnj;های مختلف مهندسی مکانیک هستند.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/mechanical-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/mechanical-engineering.png.png",
      "icon": "",
      "count_product": 68,
      "attachment_id": 265264,
      "count_student": 74917,
      "total_time": 26094,
      "total_sales": 74917,
      "total_sales_30day": 2125,
      "count_instructor": 2,
      "seo_title": "آموزش مهندسی مکانیک - گرایش های رشته مکانیک | فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی مکانیک</p>",
      "seo_metadesc": "مجموعه کامل آموزش در زمینه مهندسی مکانیک در گرایش های مختلف از مبتدی تا پیشرفته، شامل صدها ساعت آموزش تخصصی با مجرب‌ ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 1057415,
      "title": "مجموعه آموزش نرم افزارهای مهندسی برق",
      "slug": "electrical-engineering-software",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2019/03/electrical-engineering-software.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2019/03/electrical-engineering-software.svg",
      "icon": "",
      "count_product": 79,
      "attachment_id": 1064637,
      "count_student": 74640,
      "total_time": 23333,
      "total_sales": 74640,
      "total_sales_30day": 1437,
      "count_instructor": 2,
      "seo_title": "نرم افزارهای مهندسی برق | فرادرس",
      "ext_title_short": "<p>آموزش نرم افزارهای مهندسی برق</p>",
      "seo_metadesc": "مجموعه کاملی از فیلم های آموزشی نرم افزارهای مهندسی برق و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با تدریس مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 131509,
      "title": "کارشناسی ارشد مهندسی کامپیوتر",
      "slug": "university-exam-computer",
      "post_status": "draft",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/08/university-exam-computer.png",
      "png_image": "https://faradars.org/wp-content/uploads/2016/08/university-exam-computer.png",
      "icon": "",
      "count_product": 16,
      "attachment_id": 131570,
      "count_student": 74378,
      "total_time": 13752,
      "total_sales": 74378,
      "total_sales_30day": 1311,
      "count_instructor": 1,
      "seo_title": "",
      "ext_title_short": null,
      "seo_metadesc": "",
      "state_publish": "draft"
    },
    {
      "id": 280094,
      "title": "مجموعه آموزش شبکه های کامپیوتری",
      "slug": "computer-networks",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">کامپیوترها در دنیای امروزی به عضو جدایی ناپذیری از کسب و کار و تجارت تبدیل شده&zwnj;اند. کامپیوترها نه تنها در فعالیت&zwnj;های حرفه&zwnj;ای و تجاری، بلکه در کارهای روزمره شخصی نیز نقش پررنگی دارند و اهمیت آن&zwnj;ها بر هیچ کس پوشیده نیست. با تحولات ایجاد شده در دنیای فناوری، شبکه &zwnj;های کامپیوتری نیز وارد عرصه شدند و سیر پیشرفت دنیای شبکه رفته رفته از شبکه های سیمی اولیه به سمت فناوری شبکه های وایرلس سوق پیدا کرده است. تنها با اندکی تفکر می&zwnj;توان دریافت که شبکه های کامپیوتری تقریباً همه چیز را تحت تاثیر قرار داده&zwnj;اند.</p>\r\n\r\n<p style=\"text-align:justify\">شبکه کامپیوتری اتصال میان کامپیوترها است یا می&zwnj;توان گفت که شبکه کامپیوتری به گروهی از کامپیوترها گفته می&zwnj;شود که به یکدیگر متصل شده&zwnj;اند و از این طریق یک کامپیوتر می&zwnj;تواند با کامپیوتر دیگر ارتباط برقرار کند. شبکه های کامپیوتری دنیایی گسترده به حساب می&zwnj;آید که روز به روز اهمیت بیش&zwnj;تری پیدا می&zwnj;کند و نقش آن در کسب و کارها پر رنگ&zwnj;تر می&zwnj;شود. بنابراین، این حوزه بازار کار گسترده&zwnj;ای دارد و با حرفه&zwnj;ای شدن در این زمینه می&zwnj;توان به درآمد قابل قبولی دست یافت. در نتیجه باید گفت که آموزش شبکه&zwnj;های کامپیوتری ارزش صرف وقت و هزینه را دارد.</p>\r\n\r\n<p style=\"text-align:justify\">در دوره&zwnj;های تخصصی شبکه های کامپیوتری فرادرس به آموزش مدیریت شبکه، معماری شبکه، زیرساخت شبکه، عیب یابی شبکه و بسیاری از موارد دیگر پرداخته شده است. می&zwnj;توان به وسیله یادگیری مهارت&zwnj;های کاربردی شبکه با استفاده از دوره&zwnj;های جامع و کاربردی فرادرس به این حوزه از صنعت IT وارد شد و فعالیت حرفه&zwnj;ای خود را در این زمینه آغاز کرد.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2017/07/landing-horizontal.svg-1.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2017/07/landing-horizontal.svg-1.svg",
      "icon": "",
      "count_product": 44,
      "attachment_id": 310564,
      "count_student": 71347,
      "total_time": 20236,
      "total_sales": 71347,
      "total_sales_30day": 1276,
      "count_instructor": 1,
      "seo_title": "آموزش شبکه‌های کامپیوتری",
      "ext_title_short": "<p>شبکه های کامپیوتری</p>",
      "seo_metadesc": null,
      "state_publish": "publish"
    },
    {
      "id": 55068,
      "title": "مجموعه آموزش وردپرس",
      "slug": "wordpress",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/wordpress.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/wordpress.png.png",
      "icon": "",
      "count_product": 17,
      "attachment_id": 265368,
      "count_student": 71235,
      "total_time": 3951,
      "total_sales": 71235,
      "total_sales_30day": 1082,
      "count_instructor": 8,
      "seo_title": "آموزش طراحی سایت با وردپرس WordPress - مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>وردپرس WordPress</p>",
      "seo_metadesc": "ده ها ساعت فیلم آموزشی وردپرس به صورت عملی و گام به گام در فرادرس، برای راه اندازی و مدیریت انواع وبسایت، از مبتدی تا پیشرفته، و با تدریس اساتید مجرب",
      "state_publish": "publish"
    },
    {
      "id": 9208095,
      "title": "مجموعه آموزش برنامه نویسی C و C++‎",
      "slug": "c-and-c-plus-plus-programming",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2021/02/06/c_و__++c-svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2021/02/06/c_و__++c-png.png",
      "icon": "",
      "count_product": 11,
      "attachment_id": 9229385,
      "count_student": 70890,
      "total_time": 5695,
      "total_sales": 70890,
      "total_sales_30day": 1095,
      "count_instructor": 1,
      "seo_title": "آموزش کامل برنامه نویسی سی و سی پلاس پلاس | آموزش  C و C++‌‎ - مقدماتی تا پیشرفته",
      "ext_title_short": "برنامه نویسی C و C++‎",
      "seo_metadesc": "مجموعه فیلم‌ های آموزشی برنامه‌‌ نویسی سی و  سی پلاس پلاس(C++, C) به زبان فارسی، به صورت کاربردی و گام به گام، با تدریس مجرب ترین اساتید با پیاده ‌سازی پروژه های عملی",
      "state_publish": "publish"
    },
    {
      "id": 331880,
      "title": "مجموعه آموزش های علوم تجربی",
      "slug": "experimental-sciences",
      "post_status": "draft",
      "excerpt": "",
      "content": "<p style=\"text-align: justify;\">علوم تجربی خود شامل علم هایی چون زیست شناسی، زمین شناسی، فیزیک و شیمی است که هرکدام از این علوم نیز دارای مسیرها و شاخه های مربوط به خود هستند. در این بخش لیست آموزش هایی که در زمینه علوم تجربی در فرادرس ارائه شده است را جمع آوری نمودیم.</p>\r\n&nbsp;",
      "svg_image": "",
      "png_image": "",
      "icon": "",
      "count_product": 47,
      "attachment_id": null,
      "count_student": 69109,
      "total_time": 20232,
      "total_sales": 69109,
      "total_sales_30day": 1381,
      "count_instructor": 1,
      "seo_title": "",
      "ext_title_short": null,
      "seo_metadesc": "",
      "state_publish": "draft"
    },
    {
      "id": 278966,
      "title": "بزرگ‌ترین دانشکده آنلاین آموزش‌های مهندسی برق، الکترونیک و مکاترونیک",
      "slug": "saha",
      "post_status": "draft",
      "excerpt": "",
      "content": "&nbsp;\r\n<table style=\"text-align: center; margin-bottom: 20px; border-collapse: collapse; margin-left: auto; margin-right: auto; height: 80%; width: 40%;\">\r\n<tbody>\r\n<tr>\r\n<td style=\"text-align: center; border-radius: 0px;\"><img class=\"aligncenter\" style=\"display: inline-block;\" src=\"http://faradars.org/wp-content/uploads/2014/04/FaraDars-Logo-1-200.png\" alt=\"\" width=\"124px\" /></td>\r\n<td style=\"text-align: center; border-radius: 0px; width: 70px;\"></td>\r\n<td style=\"text-align: center; border-radius: 0px;\"><img class=\"aligncenter\" style=\"display: inline-block;\" src=\"http://faradars.org/wp-content/uploads/2017/07/saha-1.svg\" alt=\"\" width=\"185\" /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n&nbsp;\r\n<p style=\"text-align: center; font-size: 24px;\">فهرست آموزش‌های منتشر شده در</p>\r\n<p style=\"text-align: center; font-size: 24px;\">در پایان آخرین فاز بزرگ‌ترین دانشکده آنلاین آموزش‌های مهندسی برق، الکترونیک و مکاترونیک</p>\r\n<p style=\"text-align: center; font-size: 22px; color: #f93;\">با حمایت مالی صندوق حمايت از تحقيقات و توسعه صنايع الكترونيك (صحا)</p>\r\n<p style=\"text-align: justify;\">آموزش های ارائه شده در این صفحه، در طی یک قرارداد با حمایت مالی صندوق حمايت از تحقيقات و توسعه صنايع الكترونيك (صحا) جهت ایجاد دانشکده آنلاین آموزش‌های مهندسی برق و مکاترونیک، ارائه شده است. آموزش های ارائه شده و آموزش هایی که به زودی منتشر خواهند شد، شامل دروس مشترک و اختصاصی دوره کارشناسی و دروسی است که در دوره تحصیلات تکمیلی این رشته‌ها ارائه می‌شوند.</p>\r\n&nbsp;",
      "svg_image": "https://faradars.org/wp-content/uploads/2017/07/27.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2017/07/27.svg",
      "icon": "",
      "count_product": 35,
      "attachment_id": 562603,
      "count_student": 69042,
      "total_time": 31173,
      "total_sales": 69042,
      "total_sales_30day": 1371,
      "count_instructor": 6,
      "seo_title": "",
      "ext_title_short": null,
      "seo_metadesc": "",
      "state_publish": "draft"
    },
    {
      "id": 55444,
      "title": "مجموعه آموزش آمار و احتمالات",
      "slug": "statistics",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">آمار و احتمال علمی است که امروزه اهمیت آن بیش از هر زمان دیگری مشخص شده است. این علم اکنون پایه و اساس بسیاری از زمینه&zwnj;های پرطرفدار و روبه&zwnj;رشد از قبیل هوش مصنوعی، علم داده و یادگیری ماشین است. علاوه بر این، آمار و احتمال به حوزه بازارهای مالی و اقتصاد راه یافته و به یک ابزار بسیار کاربردی برای مهندسان مالی و اقتصاددانان تبدیل شده است. امروزه، این علم در حوزه بهداشت و پزشکی نیز نقش بسیار مهمی ایفا می&zwnj;کند. &nbsp;</p>\r\n\r\n<p style=\"text-align:justify\">آمار و احتمال با ارقام و اعداد شکل گرفته و با شمارش، مقایسه و رابطه سر و کار دارد. این دانش کاربرد علمی مبانی ریاضی در جمع&zwnj;آوری، تجزیه و تحلیل و نمایش داده&zwnj;های عددی است. بنابراین، ورود به این رشته نیازمند علاقه و البته توانایی در زمینه ریاضیات است و بهره&zwnj;گیری از رایانه نیز در آن از اهمیت بالایی برخوردار است.&nbsp;</p>\r\n\r\n<p style=\"text-align:justify\">روش&zwnj;های آماری در علوم گوناگونی مانند زیست&zwnj;شناسی، اقتصاد، مهندسی، پزشکی، بهداشت عمومی، روانشناسی، بازاریابی، آموزش، ورزش و غیره کاربرد دارند. به همین دلیل، علاقه&zwnj;مندان به رشته&zwnj;های مختلف، می&zwnj;توانند از دانش آمار در حوزه مورد علاقه خود استفاده کنند.</p>\r\n\r\n<p style=\"text-align:justify\">آموزش&zwnj;&zwnj;های آمار و احتمال فرادرس، طیف گسترده&zwnj;ای از موضوعات، از مفاهیم پایه نظری و کاربردی آمار و احتمال گرفته تا آموزش کار با نرم&zwnj;افزارهای مهم مانند R و SPSS و پایتون را در بر می&zwnj;گیرد. این آموزش&zwnj;ها توسط مدرسان باتجربه و متخصص در این زمینه تهیه شده است.&nbsp;<br />\r\n&nbsp;</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/statistics-svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/statistics-png.png",
      "icon": "",
      "count_product": 47,
      "attachment_id": 1891043,
      "count_student": 68433,
      "total_time": 19362,
      "total_sales": 68433,
      "total_sales_30day": 1295,
      "count_instructor": 2,
      "seo_title": "مجموعه آموزش آمار و احتمالات | جامع و از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>آمار و احتمالات</p>",
      "seo_metadesc": "کامل‌ ترین مجموعه فیلم ‌های آموزشی آمار و احتمالات، به همراه آموزش نرم ‌افزارهای تخصصی، توسط بهترین و مجرب‌ ترین اساتید کشور، به زبان فارسی",
      "state_publish": "publish"
    },
    {
      "id": 55472,
      "title": "مجموعه آموزش الگوریتم های بهینه سازی هوشمند",
      "slug": "intelligent-optimization-algorithms",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/optimization.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/optimization.png.png",
      "icon": "",
      "count_product": 42,
      "attachment_id": 265273,
      "count_student": 68309,
      "total_time": 11582,
      "total_sales": 68309,
      "total_sales_30day": 718,
      "count_instructor": 23,
      "seo_title": "آموزش کامل الگوریتم های بهینه سازی هوشمند - مقدماتی تا پیشرفته| فرادرس",
      "ext_title_short": "<p>الگوریتم های بهینه سازی هوشمند</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی بهینه سازی کلاسیک و هوشمند، شامل صدها ساعت آموزش تخصصی حاوی مباحث تئوری و عملی به زبان فارسی با تدریس مجرب ترین اساتید",
      "state_publish": "publish"
    },
    {
      "id": 131524,
      "title": "مجموعه آموزش دروس مهندسی برق",
      "slug": "electrical-engineering-courses",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p>&nbsp;</p>\r\n\r\n<p style=\"text-align:justify\">مهندسی برق (Electrical Engineering)، به مطالعه و بررسی موضوعات مربوط به الکترونیک، الکترومغناطیس، مخابرات و ... می پردازد. به علت استفاده روزافزون از برق و الکتریسیته، مهندسی برق به یکی از مهم ترین رشته های فنی و مهندسی تبدیل شذه است. در همین راستا، دروس مهم این رشته که برای دانشجویان و حتی فارغ التحصیلان، نقش اساسی در یادگیری و تقویت آن ها دارد به طور کامل مورد بحث و بررسی قرار گرفته است. دروسی مانند مدارهای الکتریکی، الکترونیک، ماشین های الکتریکی، الکترومغناطیس، مکاترونیک و ... توسط اساتید مجرب این حوزه در فرادرس تهیه شده است.</p>\r\n\r\n<p>&nbsp;</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/08/electrical-engineering-courses.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/08/electrical-engineering-courses.png.png",
      "icon": "",
      "count_product": 31,
      "attachment_id": 265245,
      "count_student": 68234,
      "total_time": 26948,
      "total_sales": 68234,
      "total_sales_30day": 1430,
      "count_instructor": 1,
      "seo_title": "آموزش دروس مهندسی برق - کلیه دروس و گرایش ها | فرادرس",
      "ext_title_short": "<p>دروس مهندسی برق</p>",
      "seo_metadesc": "کامل‌ترین مجموعه فیلم‌های آموزشی دروس مهندسی برق، شامل صدها ساعت آموزش تخصصی به زبان فارسی با تدریس مجرب‌ترین اساتید مهندسی برق کشور + حل سئوالات کنکور",
      "state_publish": "publish"
    },
    {
      "id": 310011,
      "title": "مجموعه آموزش ادیت و تدوین فیلم",
      "slug": "film-editing",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2022/03/02/film-editing-and-composition-svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2022/03/02/film-editing-and-composition-png.png",
      "icon": "",
      "count_product": 16,
      "attachment_id": 9250709,
      "count_student": 67609,
      "total_time": 3082,
      "total_sales": 67609,
      "total_sales_30day": 888,
      "count_instructor": 1,
      "seo_title": "ادیت و تدوین فیلم از مبتدی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>ادیت و تدوین فیلم</p>",
      "seo_metadesc": "مجموعه کاملی از فیلم های آموزشی تدوین فیلم و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 9208138,
      "title": "مجموعه آموزش ارزهای دیجیتال",
      "slug": "digital-currency",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2021/06/23/digital-currency.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2021/06/23/digital-currency.png.png",
      "icon": "",
      "count_product": 14,
      "attachment_id": 9232722,
      "count_student": 67548,
      "total_time": 5074,
      "total_sales": 67548,
      "total_sales_30day": 751,
      "count_instructor": 3,
      "seo_title": "مجموعه آموزش ارزهای دیجیتال | فرادرس",
      "ext_title_short": "<p>آموزش های ارزهای دیجیتال</p>",
      "seo_metadesc": "مجموعه آموزش ارزهای دیجیتال،  به صورت گام به گام و کاربردی با مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 55057,
      "title": "مجموعه آموزش ابزار مدیریت وب سایت",
      "slug": "webmastering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/webmastering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/webmastering.png.png",
      "icon": "",
      "count_product": 19,
      "attachment_id": 265289,
      "count_student": 66761,
      "total_time": 3907,
      "total_sales": 66761,
      "total_sales_30day": 1014,
      "count_instructor": 11,
      "seo_title": "مجموعه آموزش ابزار مدیریت وب سایت — از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>آموزش ابزارهای مدیریت وب سایت</p>",
      "seo_metadesc": "ده ها ساعت آموزش تصویری فرادرس، شامل نکات عملی و تخصصی راه اندازی، توسعه و مدیریت سایت های اینترنتی، برای وبمسترها",
      "state_publish": "publish"
    },
    {
      "id": 350527,
      "title": "مجموعه آموزش طراحی سایت با HTML و CSS",
      "slug": "html-and-css",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2019/03/htmlcss-1.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2019/03/htmlcss-1.svg",
      "icon": "",
      "count_product": 24,
      "attachment_id": 1061869,
      "count_student": 64920,
      "total_time": 4744,
      "total_sales": 64920,
      "total_sales_30day": 1062,
      "count_instructor": 5,
      "seo_title": "طراحی سایت با HTML و CSS | فرادرس",
      "ext_title_short": "<p>طراحی سایت با HTML و CSS</p>",
      "seo_metadesc": "مجموعه کاملی از فیلم های آموزشی طراحی سایت با HTML و CSS و مباحث مرتبط با آن از مبتدی تا پیشرفته، به صورت گام به گام و کاربردی با مجرب‌ ترین اساتید‎",
      "state_publish": "publish"
    },
    {
      "id": 1461655,
      "title": "مجموعه آموزش سینما",
      "slug": "cinema",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2019/07/cinema-1.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2019/07/cinema-1.svg",
      "icon": "",
      "count_product": 18,
      "attachment_id": 1462070,
      "count_student": 61464,
      "total_time": 3593,
      "total_sales": 61464,
      "total_sales_30day": 634,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش سینما (Cinema) | فرادرس",
      "ext_title_short": "<p>آموزش های سینما</p>",
      "seo_metadesc": "مجموعه آموزش های فرادرس در زمینه سینما و مباحث مرتبط با آن، شامل بیش از 40 ساعت آموزش تخصصی به زبان فارسی با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55488,
      "title": "مجموعه آموزش مهندسی کنترل",
      "slug": "control-engineering",
      "post_status": "publish",
      "excerpt": "",
      "content": "",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/control-engineering.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/control-engineering.png.png",
      "icon": "",
      "count_product": 60,
      "attachment_id": 265257,
      "count_student": 57357,
      "total_time": 30291,
      "total_sales": 57357,
      "total_sales_30day": 1064,
      "count_instructor": 5,
      "seo_title": "آموزش مهندسی برق - کنترل | فرادرس",
      "ext_title_short": "<p>آموزش های مهندسی کنترل</p>",
      "seo_metadesc": "مجموعه کامل فیلم های آموزشی مهندسی کنترل، شامل صدها ساعت آموزش تخصصی حاوی مباحث تئوری و عملی، با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    },
    {
      "id": 55052,
      "title": "مجموعه آموزش کسب و کار و استارتاپ",
      "slug": "startup-and-business",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">دوره&zwnj;های آموزشی کسب و کار به شما کمک می&zwnj;کنند تا در مهارت&zwnj;های اساسی برای موفقیت در محیط کاری مدرن، تخصص بیابید. اگر در رشته&zwnj;های کارآفرینی، استراتژی کسب و کار، بازاریابی، مالی و مدیریت زمینه دارید، این دوره&zwnj;ها و فیلم&zwnj;های آموزشی برای شما مفید خواهد بود. چه صاحب کسب و کاری کوچک باشید و چه در شرکتی بزرگ و چندملیتی کار کنید، فیلم&zwnj;های آموزشی کسب و کار فرادرس توانایی شما برای تجزیه و تحلیل و درک مشکلات کسب و کار را بهبود می&zwnj;دهند.</p>\r\n\r\n<p style=\"text-align:justify\"><br />\r\nدر دوره&zwnj;های کسب و کار مباحثی از جمله مالی، حسابداری، مدیریت و اقتصاد پوشش داده می&zwnj;شوند. مهارت&zwnj;های اصلی در کسب و کار شامل فهرست زیر است:</p>\r\n\r\n<ul>\r\n\t<li style=\"text-align:justify\">تجزیه و تحلیل مالی در سطح پایه &ndash; ساخت و تفسیر ترازنامه حسابداری</li>\r\n\t<li style=\"text-align:justify\">مهارت&zwnj;های عمومی و تخصصی در فناوری اطلاعات</li>\r\n\t<li style=\"text-align:justify\">مهارت تحقیق و جست و جو</li>\r\n\t<li style=\"text-align:justify\">خود مدیریتی و یادگیری مستقل</li>\r\n\t<li style=\"text-align:justify\">ارتباطات شفاهی و کتبی حرفه&zwnj;ای</li>\r\n\t<li style=\"text-align:justify\">ایده&zwnj;پردازی</li>\r\n\t<li style=\"text-align:justify\">کار تیمی</li>\r\n\t<li style=\"text-align:justify\">رهبری</li>\r\n\t<li style=\"text-align:justify\">حل مساله</li>\r\n\t<li style=\"text-align:justify\">تجزیه و تحلیل داده</li>\r\n\t<li style=\"text-align:justify\">توانایی شناسایی علل، روند و الگوهای سرمایه&zwnj;گذاری</li>\r\n\t<li style=\"text-align:justify\">آشنایی با بازارهای جهانی</li>\r\n</ul>\r\n\r\n<p style=\"text-align:justify\">در دوره&zwnj;های کسب و کار تمام جنبه&zwnj;های کسب و کار مورد بررسی قرار می&zwnj;گیرند. فیلم&zwnj;های آموزشی فرادرس در حوزه کسب و کار شامل مواردی از جمله مدیریت مالی، مدیریت منابع انسانی، مدیریت رفتار سازمانی، تحقیق در عملیات، مدیریت بازاریابی، بازاریابی دیجیتال و بسیاری مورد دیگر است.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2015/11/startup.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2015/11/startup.svg",
      "icon": "",
      "count_product": 58,
      "attachment_id": 1062868,
      "count_student": 56535,
      "total_time": 15506,
      "total_sales": 56535,
      "total_sales_30day": 3415,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش کسب و کار و استارتاپ (Startup) — از مقدماتی تا پیشرفته | فرادرس",
      "ext_title_short": "<p>کسب و کار و استارت آپ</p>",
      "seo_metadesc": "مجموعه فیلم‌ های آموزش کسب و کار و استارتاپ، شامل صدها ساعت آموزش تخصصی با تدریس مجرب ترین اساتید کشور، به همراه اجرای پروژه های کاربردی",
      "state_publish": "publish"
    },
    {
      "id": 132449,
      "title": "مجموعه آموزش مدیریت",
      "slug": "management",
      "post_status": "publish",
      "excerpt": "",
      "content": "<p style=\"text-align:justify\">&laquo;رهبری&raquo; را می&zwnj;توان فرآیند انگیزه بخشیدن به گروهی از افراد برای رسیدن به هدفی مشترک تعریف کرد. رهبری همچنین شامل عبور از مرزهایی که به وجود آن&zwnj;ها نیازی نیست و خطر کردن برای تبدیل چشم&zwnj;اندازها به واقعیت می&zwnj;شود. از طرف دیگر، &laquo;مدیریت&raquo; را می&zwnj;توان فرآیند رسیدن به اهداف یک سازمان از طریق استفاده بهینه از منابع در محیطی پویا دانست. به بیان ساده&zwnj;تر، مدیریت شامل استفاده از منابع موجود برای رسیدن به اهداف دشوار می&zwnj;شود.</p>\r\n\r\n<p style=\"text-align:justify\">دوره&zwnj;های آموزشی در زمینه&zwnj;های مدیریت و رهبری اغلب شامل تدریس مفاهیم مدیریت، فرهنگ سازمانی، پاداش و تشویق کارکنان، رهبری هدفمند و طریقه هدایت تیم&zwnj;هایی با کارکنانی در گروه&zwnj;های سنی متفاوت می&zwnj;شود. همچنین این دوره&zwnj;های آموزشی باعث بهبود توانایی تفکر خلاقانه و یافتن راه&zwnj;حل&zwnj;های خلاقانه و جدید برای مشکلات می&zwnj;شود.</p>\r\n\r\n<p style=\"text-align:justify\">با استفاده از فیلم&zwnj;های آموزشی فرادرس در زمینه رهبری و مدیریت می&zwnj;توانید دانشی عملی برای تحلیل نمونه&zwnj;های مدیریت و رهبری در زندگی واقعی پیدا کنید و از این دانش در مسیر شغلی خود بهره بگیرید. فیلم&zwnj;های آموزشی رهبری و مدیریت در فرادرس با ارائه منابع مختلف به مدیران تازه&zwnj;کار و باتجربه به آن&zwnj;ها در فرآیند استخدام کارکنان، الهام&zwnj;بخشی و هدایت تیم&zwnj;های مختلف، مدیریت تغییر و اثرگذاری مثبت بر ذینفعان سازمان&zwnj;ها کمک می&zwnj;کنند.</p>",
      "svg_image": "https://faradars.org/wp-content/uploads/2016/08/management-courses.svg.svg",
      "png_image": "https://faradars.org/wp-content/uploads/2016/08/management-courses.png.png",
      "icon": "",
      "count_product": 128,
      "attachment_id": 265221,
      "count_student": 55868,
      "total_time": 40977,
      "total_sales": 55868,
      "total_sales_30day": 2262,
      "count_instructor": 1,
      "seo_title": "مجموعه آموزش ‌های دروس مدیریت در گرایش های مختلف | فرادرس",
      "ext_title_short": "<p>آموزش های مدیریت</p>",
      "seo_metadesc": "کامل ترین مجموعه فیلم های آموزشی دروس مدیریت در گرایش های مختلف، شامل ده ها ساعت آموزش تخصصی به زبان فارسی با تدریس مجرب ترین اساتید کشور",
      "state_publish": "publish"
    }
]

export const landings = [...JSON.parse(JSON.stringify(jsonLandings))]