export const home_categories = [
  {
    id: 1,
    image: "/images/icons/programming.svg",
    url: "/how-to-learn/programming",
    title: "برنامه نویسی",
  },
  {
    id: 2,
    image: "/images/icons/stock-and-technical-analysis.svg",
    url: "/how-to-learn/stock-and-technical-analysis",
    title: "بورس و بازار سهام",
  },
  {
    id: 3,
    image: "/images/icons/startup-and-business.svg",
    url: "/how-to-learn/startup-and-business",
    title: "استارتاپ و کسب‌و‌کار",
  },
  {
    id: 4,
    image: "/images/icons/computer-science-and-engineering.svg",
    url: "/how-to-learn/computer-science-and-engineering",
    title: "مهندسی نرم‌افزار",
  },
  {
    id: 5,
    image: "/images/icons/artificial-intelligence.svg",
    url: "/how-to-learn/artificial-intelligence",
    title: "هوش مصنوعی",
  },
  {
    id: 6,
    image: "/images/icons/mathematics.svg",
    url: "/how-to-learn/mathematics",
    title: "ریاضیات",
  },
  {
    id: 7,
    image: "/images/icons/humanities.svg",
    url: "/how-to-learn/humanities",
    title: "علوم انسانی",
  },
  {
    id: 8,
    image: "/images/icons/art.svg",
    url: "/how-to-learn/art",
    title: "هنر",
  },
  {
    id: 9,
    image: "/images/icons/robotics.svg",
    url: "/how-to-learn/robotics",
    title: "رباتیک",
  },
  {
    id: 10,
    image: "/images/icons/statistics.svg",
    url: "/how-to-learn/statistics",
    title: "آمار و داده‌کاوی",
  },
  {
    id: 11,
    image: "/images/icons/matlab.svg",
    url: "/how-to-learn/matlab",
    title: "متلب و سیمیولینک",
  },
  {
    id: 12,
    image: "/images/icons/management.svg",
    url: "/how-to-learn/management",
    title: "مدیریت",
  },
  {
    id: 13,
    image: "/images/icons/english-language.svg",
    url: "/how-to-learn/english-language",
    title: "زبان انگلیسی",
  },
  {
    id: 14,
    image: "/images/icons/electrical-engineering.svg",
    url: "/how-to-learn/electrical-engineering",
    title: "مهندسی برق",
  },
  {
    id: 15,
    image: "/images/icons/mechanical-engineering.svg",
    url: "/how-to-learn/mechanical-engineering",
    title: "مهندسی مکانیک",
  },
  {
    id: 16,
    image: "/images/icons/civil-engineering.svg",
    url: "/how-to-learn/civil-engineering",
    title: "مهندسی عمران",
  },
  {
    id: 17,
    image: "/images/icons/architect-engineering.svg",
    url: "/how-to-learn/architect-engineering",
    title: "مهندسی معماری",
  },
  {
    id: 18,
    image: "/images/icons/control-engineering.svg",
    url: "/how-to-learn/control-engineering",
    title: "مهندسی کنترل",
  },
  {
    id: 19,
    image: "/images/icons/industrial-engineering.svg",
    url: "/how-to-learn/industrial-engineering",
    title: "مهندسی صنایع",
  },
  {
    id: 20,
    image: "/images/icons/academic-writing.svg",
    url: "/how-to-learn/academic-writing",
    title: "مدنگارش آکادمیک",
  },
  {
    id: 21,
    image: "/images/icons/microsoft-excel.svg",
    url: "/how-to-learn/microsoft-excel",
    title: "اکسل",
  },
  {
    id: 22,
    image: "/images/icons/photoshop-computer-design-and-graphics.svg",
    url: "/how-to-learn/photoshop-computer-design-and-graphics",
    title: "طراحی و گرافیک",
  },
  {
    id: 23,
    image: "/images/icons/webmastering.svg",
    url: "/how-to-learn/webmastering",
    title: "برنامه‌نویسی وب",
  },
  {
    id: 24,
    image: "/images/icons/wordpress.svg",
    url: "/how-to-learn/wordpress",
    title: "وردپرس",
  },
];
